import { useEffect, useMemo, useState } from "react";
import {
  fetchViewerOverview,
  repoEntries,
  resolveViewerLinks,
  type ViewerOverview,
} from "@/lib/repo/viewers";
import { useAnalysis } from "@/store/use-analysis-store";
import { RepoCard } from "./repo-hub";

/**
 * RepoPortal — Level 0, the single entry page for the whole platform. One
 * card per integrated repository (live numbers from each repo's manifest);
 * click → that repo's hub (architecture, specifications, pull requests) →
 * a pull request's full report. Rendered at the dedicated portal deployment
 * (viewers.json present, no repo manifest — see boot()).
 */
export default function RepoPortal() {
  const repoViewers = useAnalysis((s) => s.repoViewers);
  const repos = useMemo(
    () =>
      repoEntries(resolveViewerLinks(repoViewers, window.location.pathname)),
    [repoViewers],
  );
  const [overviews, setOverviews] = useState<
    Record<string, ViewerOverview | null>
  >({});
  useEffect(() => {
    let cancelled = false;
    for (const v of repos) {
      if (overviews[v.href] !== undefined) continue;
      void fetchViewerOverview(v.href).then((ov) => {
        if (!cancelled) setOverviews((prev) => ({ ...prev, [v.href]: ov }));
      });
    }
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [repos]);

  return (
    <div
      className="h-screen w-screen overflow-y-auto"
      style={{ background: "var(--page-bg)" }}
    >
      <div className="mx-auto w-full max-w-[1080px] px-6 pb-24 sm:px-10">
        <header
          className="animate-fade-in pt-16 pb-12 sm:pt-24"
          style={{ animationDelay: "0ms" }}
        >
          <p
            className="mb-4 font-mono text-[11px] tracking-[0.22em] uppercase"
            style={{ color: "var(--bpmn-text-dim)" }}
          >
            Underscore
          </p>
          <h1
            className="text-[40px] leading-[1.05] font-semibold sm:text-[56px]"
            style={{
              fontFamily: "var(--bpmn-font-display)",
              color: "var(--bpmn-text)",
              letterSpacing: "-0.02em",
            }}
          >
            Repositories
          </h1>
          <p
            className="mt-4 max-w-xl text-[15px] leading-relaxed"
            style={{
              fontFamily: "var(--reading-font)",
              color: "var(--bpmn-text-muted)",
            }}
          >
            Every system on this platform. Open one for its architecture,
            living specifications, and every analyzed pull request.
          </p>
        </header>

        <div
          className="animate-fade-in grid grid-cols-1 gap-4 md:grid-cols-2"
          style={{ animationDelay: "80ms" }}
        >
          {repos.map((v) => (
            <RepoCard
              key={v.href}
              name={v.name}
              href={v.href}
              active={false}
              overview={overviews[v.href] ?? null}
            />
          ))}
        </div>
        {repos.length === 0 && (
          <p
            className="rounded-lg border px-4 py-6 text-center font-mono text-[12px]"
            style={{
              borderColor: "var(--bpmn-border-soft)",
              color: "var(--bpmn-text-dim)",
            }}
          >
            No repositories are registered on this host yet.
          </p>
        )}

        <footer
          className="mt-16 border-t pt-6 font-mono text-[11px]"
          style={{
            borderColor: "var(--bpmn-border-soft)",
            color: "var(--bpmn-text-dim)",
          }}
        >
          Generated by Underscore
        </footer>
      </div>
    </div>
  );
}
